# Generated by Django 2.2.5 on 2019-09-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190921_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
