# Generated by Django 2.2.5 on 2019-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190922_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamyaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mahmud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nowsin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='post',
            new_name='Hossain',
        ),
    ]
